### ISSUE TITLE
`get_type_metrics` unable to read font `(null)`

### ISSUE THREAD

**Issue by viktorasl** [topfunky/gruff#120]
```
/Library/Ruby/Gems/2.0.0/gems/gruff-0.5.1/lib/gruff/base.rb:1112:in `get_type_metrics': unable to read font `(null)' @ error/annotate.c/RenderFreetype/1127: `(null)' (Magick::ImageMagickError)
    from /Library/Ruby/Gems/2.0.0/gems/gruff-0.5.1/lib/gruff/base.rb:1112:in `calculate_caps_height'
    from /Library/Ruby/Gems/2.0.0/gems/gruff-0.5.1/lib/gruff/base.rb:523:in `setup_graph_measurements'
    from /Library/Ruby/Gems/2.0.0/gems/gruff-0.5.1/lib/gruff/base.rb:485:in `setup_drawing'
    from /Library/Ruby/Gems/2.0.0/gems/gruff-0.5.1/lib/gruff/base.rb:450:in `draw'
    from /Library/Ruby/Gems/2.0.0/gems/gruff-0.5.1/lib/gruff/line.rb:174:in `draw'
    from /Library/Ruby/Gems/2.0.0/gems/gruff-0.5.1/lib/gruff/base.rb:424:in `write'
    from histogram.rb:12:in `<main>'
```

I believe it is missing `ghostscript` dependency.

**Comment by trishume** [comment]
I encountered this issue as well.

**Comment by trishume** [comment]
`brew install ghostscript` fixed the problem. :+1:

**Comment by lepirlouit** [comment]
`sudo apt-get install ghostscript`

**Comment by viktorasl** [comment]
Is it still appearing?

**Comment by eric1234** [comment]
If you are using Alpine Linux (primarily to run in docker) the fonts are in a separate package:

```
apk add ghostscript ghostscript-fonts
```

**Comment by stats** [comment]
I am having this issue on macOS Sierra version 10.12.1

I have installed imagemagick and ghostscript using
```
brew install imagemagick
brew install ghostscript
```

The error I am getting is a little different

```
.rvm/gems/ruby-2.3.0/gems/gruff-0.7.0/lib/gruff/base.rb:1126:in `get_type_metrics': unable to open image `ps:/var/folders/cc/kxmtwwxj5hs_k_z5g6m0n1940000gn/T/magick-BHkU3Xaz': No such file or directory @ error/blob.c/OpenBlob/2484: `(null)' (Magick::ImageMagickError)
	from .rvm/gems/ruby-2.3.0/gems/gruff-0.7.0/lib/gruff/base.rb:1126:in `calculate_caps_height'
	from .rvm/gems/ruby-2.3.0/gems/gruff-0.7.0/lib/gruff/base.rb:537:in `setup_graph_measurements'
	from .rvm/gems/ruby-2.3.0/gems/gruff-0.7.0/lib/gruff/base.rb:499:in `setup_drawing'
	from .rvm/gems/ruby-2.3.0/gems/gruff-0.7.0/lib/gruff/base.rb:464:in `draw'
	from .rvm/gems/ruby-2.3.0/gems/gruff-0.7.0/lib/gruff/line.rb:184:in `draw'
	from .rvm/gems/ruby-2.3.0/gems/gruff-0.7.0/lib/gruff/base.rb:438:in `write'
	from main.rb:11:in `<main>'
```

The file referenced does exist and it is a postscript X.

Not sure what else can be done to get around this issue.

**Comment by noraj** [comment]
```
/home/noraj/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/gruff-0.12.1/lib/gruff/renderer/text.rb:54:in `get_type_metrics': unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1425 (Magick::ImageMagickError)
```

On ArchLinux `pacman -S ghostscript` doesn't solve the issue nor `pacman -S tex-gyre-fonts` (free substitute for Helvetica).
