### ISSUE TITLE
no decode delegate for this image format `'

### ISSUE THREAD

**Issue by derrelldurrett** [topfunky/gruff#464]
In trying to setup a minimal graph, I used the tests as examples.

```
g = Gruff::Line.new('1024x1024')
g.dataxy('',[[3000, 4000], [20000, 21000]])
g.dataxy('',[[0, 10000], [10000, 0]])
g.write("/tmp/gruff.out")
Magick::ImageMagickError (no decode delegate for this image format `' @ error/constitute.c/ReadImage/562)
	from /home/derrell/.rvm/gems/ruby-2.7.1/gems/gruff-0.11.0/lib/gruff/renderer/text.rb:50:in `get_type_metrics'
	from /home/derrell/.rvm/gems/ruby-2.7.1/gems/gruff-0.11.0/lib/gruff/renderer/text.rb:50:in `metrics'
	from /home/derrell/.rvm/gems/ruby-2.7.1/gems/gruff-0.11.0/lib/gruff/base.rb:871:in `calculate_caps_height'
	from /home/derrell/.rvm/gems/ruby-2.7.1/gems/gruff-0.11.0/lib/gruff/base.rb:749:in `setup_marker_caps_height'
	from /home/derrell/.rvm/gems/ruby-2.7.1/gems/gruff-0.11.0/lib/gruff/base.rb:507:in `setup_graph_measurements'
	from /home/derrell/.rvm/gems/ruby-2.7.1/gems/gruff-0.11.0/lib/gruff/base.rb:469:in `setup_drawing'
	from /home/derrell/.rvm/gems/ruby-2.7.1/gems/gruff-0.11.0/lib/gruff/base.rb:442:in `draw'
	from /home/derrell/.rvm/gems/ruby-2.7.1/gems/gruff-0.11.0/lib/gruff/line.rb:176:in `draw'
	from /home/derrell/.rvm/gems/ruby-2.7.1/gems/gruff-0.11.0/lib/gruff/base.rb:417:in `write'
	from (irb):5
```
This is ImageMagick 7.0.10, RMagick 4.1.2, Gruff 0.11, Ruby 2.7.1, Ubuntu 20.04. If there's anything else I can provide that would be useful to debug, let me know. It's my first time playing with Gruff, so it's entirely possible a configuration setting was missed or the like.

**Comment by derrelldurrett** [comment]
So, I'm going to close this, as it appears this is a problem with my ImageMagick install (though I don't know what exactly).

**Comment by Watson1978** [comment]
Please specify the correct file extension for the image file.
`g.write("/tmp/gruff.png")`

**Comment by derrelldurrett** [comment]
That might have been the only thing, if I'd had ImageMagick installed with the PNG delegate, but I had not.
